# More on Arrays

In this lecture, we will look at the following concepts:

- Arrays (vectors, matrices and more)
- Reshaping an array
- Broadcasting rules
- Slicing an array
- Stacking arrays
- Sum, mean and variance along axes

In [1]:
import numpy as np

## Arrays

It should have become amply clear by now that both vectors and matrices are `NumPy` arrays. Each array in `NumPy` has a dimension. Vectors are one-dimensional arrays while matrices are two-dimensional arrays. For example:

$$
\mathbf{x} = \begin{bmatrix}
1\\
2\\
3
\end{bmatrix}, 
\mathbf{M} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}
$$

`NumPy` arrays have an attribute called `ndim` that gives the number of dimensions of the array:

In [2]:
x = np.array([1, 2, 3])
M = np.array([[1, 2], [3, 4], [5, 6]])

print('x has shape', x.shape)
print('M has shape', M.shape)

print('x is an array of dimension', x.ndim)
print('M is an array of dimension', M.ndim)

x has shape (3,)
M has shape (3, 2)
x is an array of dimension 1
M is an array of dimension 2


Though we will mostly restrict ourselves to arrays of dimension 2, nothing stops us from working with higher dimensional arrays. For example, consider a 3-dimensional array. This could be visualized as a list of matrices:

$$
\begin{bmatrix}
\begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8\\
9 & 10 & 11 & 12
\end{bmatrix}\\ 
\begin{bmatrix}
13 & 14 & 15 & 16\\
17 & 18 & 19 & 20\\
21 & 22 & 23 & 24
\end{bmatrix}\\
\end{bmatrix}
$$

This would be a $2 \times 3 \times 4$ array. In `NumPy` this becomes: 

In [3]:
M = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]], 
               [[13, 14, 15, 16],
               [17, 18, 19, 20],
               [21, 22, 23, 24]]
              ])
print(M.shape)
print(M.ndim)
print(M)

(2, 3, 4)
3
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


You can safely skip the 3D part if you find it difficult the first time.

## Reshaping

Arrays can be reshaped. We will start with an example. Let us start with a matrix $\mathbf{M}$:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

We can now reshape it into a vector:

$$
\mathbf{x} = \begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6
\end{bmatrix}
$$



In [4]:
M = np.array([[1, 2, 3], [4, 5, 6]])
x = M.reshape(6)
x

array([1, 2, 3, 4, 5, 6])

Note that the contents of the array are the same, but they have been rearranged. We can also go the other way, from vector to matrix:

$$
\mathbf{x} = \begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6
\end{bmatrix}
$$

We can reshape it into the following matrix:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}
$$

In [5]:
x = np.array([1, 2, 3, 4, 5, 6])
M = x.reshape((3, 2))
M

array([[1, 2],
       [3, 4],
       [5, 6]])

We can reshape a matrix into another matrix as well. Sometimes, we may not want to specify the dimensions completely. In such cases, we can let `NumPy` figure it out. For example

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

Let us say we want to reshape it in such a way that there are three rows:

$$
\mathbf{P} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}
$$



In [6]:
M = np.array([[1, 2, 3], [4, 5, 6]])
P = M.reshape((3, -1))
P

array([[1, 2],
       [3, 4],
       [5, 6]])

$-1$ refers to the unknown dimension, which we let `NumPy` compute.

## Matrix-vector addition (broadcasting)

In many ML models, we would have to add a vector to each row or column of a matrix. For example, consider the following case for row-wise addition:


### Row-wise addition

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8
\end{bmatrix}, \mathbf{b} = \begin{bmatrix}
1 & 1 & 1 & 1
\end{bmatrix}
$$

This is slight abuse of notation as we can't add a matrix and a vector together. However, the context often makes this clear:

$$
\mathbf{M} + \mathbf{b} = \begin{bmatrix}
2 & 3 & 4 & 5\\
6 & 7 & 8 & 9
\end{bmatrix}
$$

In `NumPy` this becomes:

In [7]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([1, 1, 1, 1])
print('Shape of M:', M.shape)
print('Shape of b:', b.shape)

M + b

Shape of M: (2, 4)
Shape of b: (4,)


array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

Notice how simple this is. Let us now do a slight variation. Let us say we wish to add a vector to each column of $\mathbf{M}$:

## Column-wise addition

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8
\end{bmatrix}, \mathbf{b} = \begin{bmatrix}
1\\
2
\end{bmatrix}
$$

In the case, we have:

$$
\mathbf{M} + \mathbf{b} = \begin{bmatrix}
2 & 3 & 4 & 5\\
7 & 8 & 9 & 10
\end{bmatrix}
$$

Let us see if the same syntax works:

In [11]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([1, 2])
print('Shape of M:', M.shape)
print('Shape of b:', b.shape)

### Caution! ###
# You can uncomment the next line and see what happens
M + b
### Caution! ###

Shape of M: (2, 4)
Shape of b: (2,)


ValueError: ignored

If you uncomment it and run it, you get a ValueError. Notice that the same syntax doesn't work. The error is suggestive:

> operands could not be broadcast together with shapes `(2, 4)` and `(2, )`

We will first discuss a way to fix this and then move onto why this behaviour is observed.


In [12]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([1, 2])
print('Shape of M:', M.shape)
print('Shape of b before adding dimension:', b.shape)
b = np.expand_dims(b, 1)
print('Shape of b after adding dimension:', b.shape)

M + b

Shape of M: (2, 4)
Shape of b before adding dimension: (2,)
Shape of b after adding dimension: (2, 1)


array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

`np.expand_dims` expands the dimension of a `NumPy` array. The first argument is the array and the second argument is the axis along which the array has to be expanded. Here, we want to treat `b` as a column vector. This is nothing but a `(2, 1)` matrix. So, the second argument is 1 (zero-indexing).

But why is this necessary? For adding a row vector to a matrix, we just had to use `M + b`. For adding a column vector to a matrix, we had to add an extra dimension to `b` and then add it to `M`. The answer to this lies with something called broadcasting.


### Broadcasting

When two arrays of different dimensions are combined together using an arithmetic operation such as `+`, `NumPy` sees if it can **broadcast** them. This is best understood with images. Here is an example from the `NumPy` docs on row-wise addition:

![](https://numpy.org/doc/stable/_images/broadcasting_2.png)

**Source**: https://numpy.org/doc/stable/user/basics.broadcasting.html

For column-wise addition, simple addition doesn't work:

![](https://numpy.org/doc/stable/_images/broadcasting_3.png)

**Source**: https://numpy.org/doc/stable/user/basics.broadcasting.html

In this course, we will mainly stick to matrix-vector addition or multiplication. This is the recipe:

- Row-wise
  - `M + b`
- Column-wise: 
  - Make `b` a column vector or a `(m, 1)` matrix using `np.expand_dims`
  - `M + b`

## Indexing and Slicing an array

Just like lists in Python, `NumPy` arrays can be indexed and sliced. Slicing is useful if we want to work with a portion of an array. For example, consider the matrix $\mathbf{M}$:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6\\
7 & 8\\
9 & 10
\end{bmatrix}
$$

The third row of this matrix is `M[2]`. This is just basic indexing.

In [13]:
M = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
M[2]

array([5, 6])

This behaviour is similar to what happens with Python lists. Let us say that we wish to extract the second column of this matrix. How would we do this?

In [28]:
M = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
M[:, 1]

array([ 2,  4,  6,  8, 10])

An $n$-dimensional array has $n$ axes. In the case of a matrix, a $2$D array, the first axis (index 0) refers to the rows and the second axis (index 1) refers to the columns.

In the example given above, `M[:, 1]`, the second axis is fixed as 1 while the first axis is fluid. In more concrete terms, we have selected the second column. Had we wanted a particular element, say the first element, from the second column, we would have used the notation `M[0, 1]`. But, since we want all the elements from the second column, we use the `:` operator without specifiying the start and end indices. Recall that this behaviour is similar to Python lists. If `L` is a list, then `L[:]` represents the completel list.

Now, consider the same matrix $\mathbf{M}$. We want to extract the third and fourth rows of this matrix. How do we do that?

In [26]:
M = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
M[2: 4]

array([[5, 6],
       [7, 8]])

This is again similar to the Python slicing notation. Now, if we wanted the second and third elements in the first column of the matrix, this is what we would do:

In [29]:
M = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
M[1: 3, 0]

array([3, 5])

## Stacking arrays

Sometimes, we would want to stack arrays. Consider the two matrices:

$$
\mathbf{A} =
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix},
\mathbf{B} =
\begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$

There are two ways to stack these two matrices:

### Row-wise

We could stack the two matrices along the rows, $\mathbf{A}$ on top of $\mathbf{B}$:

$$
\mathbf{C} =
\begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6\\
7 & 8
\end{bmatrix}
$$

This would be done as follows:

In [30]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.concatenate((A, B), axis = 0)
print(C.shape)
print(C)

(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Column-wise

We could stack the two matrices along the columns, $\mathbf{A}$ to the left of $\mathbf{B}$:

$$
\mathbf{C} =
\begin{bmatrix}
1 & 2 & 5 & 6\\
3 & 4 & 7 & 8\\
\end{bmatrix}
$$

This would be done as follows:

In [31]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.concatenate((A, B), axis = 1)
print(C.shape)
print(C)

(2, 4)
[[1 2 5 6]
 [3 4 7 8]]


## Sum, Mean and Variance

Sometimes we may wish to compute the sum of a particular slice of an array. For example, consider the matrix:

$$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8
\end{bmatrix}
$$

The sum of the rows of the matrix is a vector:

$$
\text{rsum}(\mathbf{A}) = \begin{bmatrix}
10\\
26
\end{bmatrix}
$$

In `NumPy` this can be done as follows:

In [32]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
rsum = np.sum(A, axis = 1)
rsum

array([10, 26])

We have added the elements of the array along the axis $1$. This has the same effect as summing the rows of the array. Now, we shall move to the column sum:

$$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8
\end{bmatrix}
$$

The sum of the columns of the matrix is a vector:

$$
\text{csum}(\mathbf{A}) = \begin{bmatrix}
6\\
8\\
10\\
12
\end{bmatrix}
$$

In [33]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
csum = np.sum(A, axis = 0)
csum

array([ 6,  8, 10, 12])

It is important to note that `sum` is an attribute of `NumPy` arrays. So we can also express this as:

In [34]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
rsum = A.sum(axis = 1)
csum = A.sum(axis = 0)

print('Sum of the rows:', rsum)
print('Sum of the columns:', csum)

Sum of the rows: [10 26]
Sum of the columns: [ 6  8 10 12]


Just like `sum`, we have `mean` to find out the mean of parts of an array.

In [39]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
rmean = A.mean(axis=1)
cmean = A.mean(axis=0)

print('Mean of the rows:', rmean)
print('Mean of the columns:', cmean)

Mean of the rows: [2.5 6.5]
Mean of the columns: [3. 4. 5. 6.]


In [40]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
rvar = A.var(axis=1)
cvar = A.var(axis=0)

print('Variance of the rows:', rvar)
print('Variance of the columns:', cvar)

Variance of the rows: [1.25 1.25]
Variance of the columns: [4. 4. 4. 4.]
